services:
  ems-dev:
    # restart: always
    image: ems-dev
    build:
      context: .
      dockerfile: Dockerfile
      # no_cache: true
    # container_name: ems-dev
    environment:
      - TZ=Asia/Taipei
      - HOST_IP=192.168.1.12
    volumes:
      # - ./router:/usr/src/app/router # Mount the <local directory>:<container directory>
      - ./router:/usr/src/app/router
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
    ports:
      - "3030-3036:3000"
    # environment:
    # - POSTGRES_NAME=postgres
    # - POSTGRES_USER=postgres
    # - POSTGRES_PASSWORD=postgres
    command: ["tail", "-f", "/dev/null"]
    deploy:
      replicas: 6 # Set the desired number of replicas
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # healthcheck:
    #   test: ["CMD", "curl", "-fs", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
    networks:
      - dev-network

networks:
  dev-network:
    external: false
